// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpBI5V2N28SDqWB-RGOM_VVnCPU-4ngQ',
    appId: '1:531580811527:web:f40887c6c5a8532b1cada2',
    messagingSenderId: '531580811527',
    projectId: 'nlpress',
    authDomain: 'nlpress.firebaseapp.com',
    storageBucket: 'nlpress.appspot.com',
    measurementId: 'G-KT133M0V3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB282EtIOe9Sbn8DyC6I7weCJQ4y1y8sn0',
    appId: '1:531580811527:android:8026b7cbe3d2d7811cada2',
    messagingSenderId: '531580811527',
    projectId: 'nlpress',
    storageBucket: 'nlpress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyrT-bwJxuOovzbgD2BEl-KNvLExsA_lM',
    appId: '1:531580811527:ios:e170a7f12e97bd461cada2',
    messagingSenderId: '531580811527',
    projectId: 'nlpress',
    storageBucket: 'nlpress.appspot.com',
    iosBundleId: 'com.example.group3Prototype',
  );
}
